import type { Locale } from "./i18n";

/** 地理分组类型 */
export type RegionGroup =
  | "asia-pacific"
  | "europe"
  | "americas"
  | "middle-east-africa";

/** 分组中文名映射 */
export const REGION_GROUP_NAMES: Record<RegionGroup, string> = {
  "asia-pacific": "亚太地区",
  europe: "欧洲",
  americas: "美洲",
  "middle-east-africa": "中东与非洲",
};

/** Apple App Store 支持的国家/地区及其货币 */
export interface Region {
  code: string; // ISO 两位国家代码
  name: string; // 中文名称
  nameEn: string; // 英文名称
  nameJa: string; // 日文名称
  nameKo: string; // 韩文名称
  nameOriginal: string; // Apple 页面原文名称
  currency: string; // 货币代码
  flag: string; // emoji 旗帜
  group: RegionGroup; // 地理分组
  appleUrl: string; // Apple 链接
}

/** 根据 ISO 两位国家代码生成 emoji 旗帜 */
function flag(code: string): string {
  return String.fromCodePoint(
    ...code
      .toUpperCase()
      .split("")
      .map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}

export const REGIONS: Region[] = [
  // ============ 亚太地区 ============
  {
    code: "cn",
    name: "中国大陆",
    nameEn: "China mainland",
    nameJa: "中国本土",
    nameKo: "중국 본토",
    nameOriginal: "中国大陆",
    currency: "CNY",
    flag: flag("CN"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com.cn/",
  },
  {
    code: "hk",
    name: "香港",
    nameEn: "Hong Kong",
    nameJa: "香港",
    nameKo: "홍콩",
    nameOriginal: "香港",
    currency: "HKD",
    flag: flag("HK"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/hk/",
  },
  {
    code: "tw",
    name: "台湾",
    nameEn: "Taiwan",
    nameJa: "台湾",
    nameKo: "대만",
    nameOriginal: "台灣",
    currency: "TWD",
    flag: flag("TW"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/tw/",
  },
  {
    code: "mo",
    name: "澳门",
    nameEn: "Macao",
    nameJa: "マカオ",
    nameKo: "마카오",
    nameOriginal: "澳門",
    currency: "MOP",
    flag: flag("MO"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/mo/",
  },
  {
    code: "jp",
    name: "日本",
    nameEn: "Japan",
    nameJa: "日本",
    nameKo: "일본",
    nameOriginal: "日本",
    currency: "JPY",
    flag: flag("JP"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/jp/",
  },
  {
    code: "kr",
    name: "韩国",
    nameEn: "South Korea",
    nameJa: "韓国",
    nameKo: "한국",
    nameOriginal: "대한민국",
    currency: "KRW",
    flag: flag("KR"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/kr/",
  },
  {
    code: "sg",
    name: "新加坡",
    nameEn: "Singapore",
    nameJa: "シンガポール",
    nameKo: "싱가포르",
    nameOriginal: "Singapore",
    currency: "SGD",
    flag: flag("SG"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/sg/",
  },
  {
    code: "au",
    name: "澳大利亚",
    nameEn: "Australia",
    nameJa: "オーストラリア",
    nameKo: "호주",
    nameOriginal: "Australia",
    currency: "AUD",
    flag: flag("AU"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/au/",
  },
  {
    code: "nz",
    name: "新西兰",
    nameEn: "New Zealand",
    nameJa: "ニュージーランド",
    nameKo: "뉴질랜드",
    nameOriginal: "New Zealand",
    currency: "NZD",
    flag: flag("NZ"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/nz/",
  },
  {
    code: "in",
    name: "印度",
    nameEn: "India",
    nameJa: "インド",
    nameKo: "인도",
    nameOriginal: "India",
    currency: "INR",
    flag: flag("IN"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/in/",
  },
  {
    code: "id",
    name: "印度尼西亚",
    nameEn: "Indonesia",
    nameJa: "インドネシア",
    nameKo: "인도네시아",
    nameOriginal: "Indonesia",
    currency: "IDR",
    flag: flag("ID"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/id/",
  },
  {
    code: "th",
    name: "泰国",
    nameEn: "Thailand",
    nameJa: "タイ",
    nameKo: "태국",
    nameOriginal: "ไทย",
    currency: "THB",
    flag: flag("TH"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/th/",
  },
  {
    code: "vn",
    name: "越南",
    nameEn: "Vietnam",
    nameJa: "ベトナム",
    nameKo: "베트남",
    nameOriginal: "Việt Nam",
    currency: "VND",
    flag: flag("VN"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/vn/",
  },
  {
    code: "my",
    name: "马来西亚",
    nameEn: "Malaysia",
    nameJa: "マレーシア",
    nameKo: "말레이시아",
    nameOriginal: "Malaysia",
    currency: "MYR",
    flag: flag("MY"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/my/",
  },
  {
    code: "ph",
    name: "菲律宾",
    nameEn: "Philippines",
    nameJa: "フィリピン",
    nameKo: "필리핀",
    nameOriginal: "Philippines",
    currency: "PHP",
    flag: flag("PH"),
    group: "asia-pacific",
    appleUrl: "https://www.apple.com/ph/",
  },

  // ============ 美洲 ============
  {
    code: "us",
    name: "美国",
    nameEn: "United States",
    nameJa: "アメリカ",
    nameKo: "미국",
    nameOriginal: "United States",
    currency: "USD",
    flag: flag("US"),
    group: "americas",
    appleUrl: "https://www.apple.com/",
  },
  {
    code: "ca",
    name: "加拿大",
    nameEn: "Canada",
    nameJa: "カナダ",
    nameKo: "캐나다",
    nameOriginal: "Canada",
    currency: "CAD",
    flag: flag("CA"),
    group: "americas",
    appleUrl: "https://www.apple.com/ca/",
  },
  {
    code: "mx",
    name: "墨西哥",
    nameEn: "Mexico",
    nameJa: "メキシコ",
    nameKo: "멕시코",
    nameOriginal: "México",
    currency: "MXN",
    flag: flag("MX"),
    group: "americas",
    appleUrl: "https://www.apple.com/mx/",
  },
  {
    code: "br",
    name: "巴西",
    nameEn: "Brazil",
    nameJa: "ブラジル",
    nameKo: "브라질",
    nameOriginal: "Brasil",
    currency: "BRL",
    flag: flag("BR"),
    group: "americas",
    appleUrl: "https://www.apple.com/br/",
  },
  {
    code: "cl",
    name: "智利",
    nameEn: "Chile",
    nameJa: "チリ",
    nameKo: "칠레",
    nameOriginal: "Chile",
    currency: "CLP",
    flag: flag("CL"),
    group: "americas",
    appleUrl: "https://www.apple.com/cl/",
  },
  {
    code: "co",
    name: "哥伦比亚",
    nameEn: "Colombia",
    nameJa: "コロンビア",
    nameKo: "콜롬비아",
    nameOriginal: "Colombia",
    currency: "COP",
    flag: flag("CO"),
    group: "americas",
    appleUrl: "https://www.apple.com/co/",
  },
  {
    code: "ar",
    name: "阿根廷",
    nameEn: "Argentina",
    nameJa: "アルゼンチン",
    nameKo: "아르헨티나",
    nameOriginal: "Argentina",
    currency: "ARS",
    flag: flag("AR"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "pe",
    name: "秘鲁",
    nameEn: "Peru",
    nameJa: "ペルー",
    nameKo: "페루",
    nameOriginal: "Perú",
    currency: "PEN",
    flag: flag("PE"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "cr",
    name: "哥斯达黎加",
    nameEn: "Costa Rica",
    nameJa: "コスタリカ",
    nameKo: "코스타리카",
    nameOriginal: "Costa Rica",
    currency: "USD",
    flag: flag("CR"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "ec",
    name: "厄瓜多尔",
    nameEn: "Ecuador",
    nameJa: "エクアドル",
    nameKo: "에콰도르",
    nameOriginal: "Ecuador",
    currency: "USD",
    flag: flag("EC"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "gt",
    name: "危地马拉",
    nameEn: "Guatemala",
    nameJa: "グアテマラ",
    nameKo: "과테말라",
    nameOriginal: "Guatemala",
    currency: "USD",
    flag: flag("GT"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "sv",
    name: "萨尔瓦多",
    nameEn: "El Salvador",
    nameJa: "エルサルバドル",
    nameKo: "엘살바도르",
    nameOriginal: "El Salvador",
    currency: "USD",
    flag: flag("SV"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "hn",
    name: "洪都拉斯",
    nameEn: "Honduras",
    nameJa: "ホンジュラス",
    nameKo: "온두라스",
    nameOriginal: "Honduras",
    currency: "USD",
    flag: flag("HN"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "pa",
    name: "巴拿马",
    nameEn: "Panama",
    nameJa: "パナマ",
    nameKo: "파나마",
    nameOriginal: "Panamá",
    currency: "USD",
    flag: flag("PA"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "py",
    name: "巴拉圭",
    nameEn: "Paraguay",
    nameJa: "パラグアイ",
    nameKo: "파라과이",
    nameOriginal: "Paraguay",
    currency: "USD",
    flag: flag("PY"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "do",
    name: "多米尼加",
    nameEn: "Dominican Republic",
    nameJa: "ドミニカ共和国",
    nameKo: "도미니카 공화국",
    nameOriginal: "República Dominicana",
    currency: "USD",
    flag: flag("DO"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "ni",
    name: "尼加拉瓜",
    nameEn: "Nicaragua",
    nameJa: "ニカラグア",
    nameKo: "니카라과",
    nameOriginal: "Nicaragua",
    currency: "USD",
    flag: flag("NI"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "uy",
    name: "乌拉圭",
    nameEn: "Uruguay",
    nameJa: "ウルグアイ",
    nameKo: "우루과이",
    nameOriginal: "Uruguay",
    currency: "USD",
    flag: flag("UY"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "bo",
    name: "玻利维亚",
    nameEn: "Bolivia",
    nameJa: "ボリビア",
    nameKo: "볼리비아",
    nameOriginal: "Bolivia",
    currency: "USD",
    flag: flag("BO"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },
  {
    code: "ve",
    name: "委内瑞拉",
    nameEn: "Venezuela",
    nameJa: "ベネズエラ",
    nameKo: "베네수엘라",
    nameOriginal: "Venezuela",
    currency: "USD",
    flag: flag("VE"),
    group: "americas",
    appleUrl: "https://www.apple.com/la/",
  },

  // ============ 欧洲 ============
  {
    code: "gb",
    name: "英国",
    nameEn: "United Kingdom",
    nameJa: "イギリス",
    nameKo: "영국",
    nameOriginal: "United Kingdom",
    currency: "GBP",
    flag: flag("GB"),
    group: "europe",
    appleUrl: "https://www.apple.com/uk/",
  },
  {
    code: "de",
    name: "德国",
    nameEn: "Germany",
    nameJa: "ドイツ",
    nameKo: "독일",
    nameOriginal: "Deutschland",
    currency: "EUR",
    flag: flag("DE"),
    group: "europe",
    appleUrl: "https://www.apple.com/de/",
  },
  {
    code: "fr",
    name: "法国",
    nameEn: "France",
    nameJa: "フランス",
    nameKo: "프랑스",
    nameOriginal: "France",
    currency: "EUR",
    flag: flag("FR"),
    group: "europe",
    appleUrl: "https://www.apple.com/fr/",
  },
  {
    code: "it",
    name: "意大利",
    nameEn: "Italy",
    nameJa: "イタリア",
    nameKo: "이탈리아",
    nameOriginal: "Italia",
    currency: "EUR",
    flag: flag("IT"),
    group: "europe",
    appleUrl: "https://www.apple.com/it/",
  },
  {
    code: "es",
    name: "西班牙",
    nameEn: "Spain",
    nameJa: "スペイン",
    nameKo: "스페인",
    nameOriginal: "España",
    currency: "EUR",
    flag: flag("ES"),
    group: "europe",
    appleUrl: "https://www.apple.com/es/",
  },
  {
    code: "nl",
    name: "荷兰",
    nameEn: "Netherlands",
    nameJa: "オランダ",
    nameKo: "네덜란드",
    nameOriginal: "Nederland",
    currency: "EUR",
    flag: flag("NL"),
    group: "europe",
    appleUrl: "https://www.apple.com/nl/",
  },
  {
    code: "se",
    name: "瑞典",
    nameEn: "Sweden",
    nameJa: "スウェーデン",
    nameKo: "스웨덴",
    nameOriginal: "Sverige",
    currency: "SEK",
    flag: flag("SE"),
    group: "europe",
    appleUrl: "https://www.apple.com/se/",
  },
  {
    code: "no",
    name: "挪威",
    nameEn: "Norway",
    nameJa: "ノルウェー",
    nameKo: "노르웨이",
    nameOriginal: "Norge",
    currency: "NOK",
    flag: flag("NO"),
    group: "europe",
    appleUrl: "https://www.apple.com/no/",
  },
  {
    code: "dk",
    name: "丹麦",
    nameEn: "Denmark",
    nameJa: "デンマーク",
    nameKo: "덴마크",
    nameOriginal: "Danmark",
    currency: "DKK",
    flag: flag("DK"),
    group: "europe",
    appleUrl: "https://www.apple.com/dk/",
  },
  {
    code: "ch",
    name: "瑞士",
    nameEn: "Switzerland",
    nameJa: "スイス",
    nameKo: "스위스",
    nameOriginal: "Schweiz",
    currency: "CHF",
    flag: flag("CH"),
    group: "europe",
    appleUrl: "https://www.apple.com/ch/",
  },
  {
    code: "pl",
    name: "波兰",
    nameEn: "Poland",
    nameJa: "ポーランド",
    nameKo: "폴란드",
    nameOriginal: "Polska",
    currency: "PLN",
    flag: flag("PL"),
    group: "europe",
    appleUrl: "https://www.apple.com/pl/",
  },
  {
    code: "tr",
    name: "土耳其",
    nameEn: "Turkey",
    nameJa: "トルコ",
    nameKo: "튀르키예",
    nameOriginal: "Türkiye",
    currency: "TRY",
    flag: flag("TR"),
    group: "europe",
    appleUrl: "https://www.apple.com/tr/",
  },
  {
    code: "ru",
    name: "俄罗斯",
    nameEn: "Russia",
    nameJa: "ロシア",
    nameKo: "러시아",
    nameOriginal: "Россия",
    currency: "RUB",
    flag: flag("RU"),
    group: "europe",
    appleUrl: "https://www.apple.com/ru/",
  },
  {
    code: "at",
    name: "奥地利",
    nameEn: "Austria",
    nameJa: "オーストリア",
    nameKo: "오스트리아",
    nameOriginal: "Österreich",
    currency: "EUR",
    flag: flag("AT"),
    group: "europe",
    appleUrl: "https://www.apple.com/at/",
  },
  {
    code: "be",
    name: "比利时",
    nameEn: "Belgium",
    nameJa: "ベルギー",
    nameKo: "벨기에",
    nameOriginal: "Belgique",
    currency: "EUR",
    flag: flag("BE"),
    group: "europe",
    appleUrl: "https://www.apple.com/be/",
  },
  {
    code: "pt",
    name: "葡萄牙",
    nameEn: "Portugal",
    nameJa: "ポルトガル",
    nameKo: "포르투갈",
    nameOriginal: "Portugal",
    currency: "EUR",
    flag: flag("PT"),
    group: "europe",
    appleUrl: "https://www.apple.com/pt/",
  },
  {
    code: "ie",
    name: "爱尔兰",
    nameEn: "Ireland",
    nameJa: "アイルランド",
    nameKo: "아일랜드",
    nameOriginal: "Ireland",
    currency: "EUR",
    flag: flag("IE"),
    group: "europe",
    appleUrl: "https://www.apple.com/ie/",
  },
  {
    code: "fi",
    name: "芬兰",
    nameEn: "Finland",
    nameJa: "フィンランド",
    nameKo: "핀란드",
    nameOriginal: "Suomi",
    currency: "EUR",
    flag: flag("FI"),
    group: "europe",
    appleUrl: "https://www.apple.com/fi/",
  },
  {
    code: "gr",
    name: "希腊",
    nameEn: "Greece",
    nameJa: "ギリシャ",
    nameKo: "그리스",
    nameOriginal: "Greece",
    currency: "EUR",
    flag: flag("GR"),
    group: "europe",
    appleUrl: "https://www.apple.com/gr/",
  },
  {
    code: "cz",
    name: "捷克",
    nameEn: "Czech Republic",
    nameJa: "チェコ",
    nameKo: "체코",
    nameOriginal: "Česko",
    currency: "CZK",
    flag: flag("CZ"),
    group: "europe",
    appleUrl: "https://www.apple.com/cz/",
  },
  {
    code: "hu",
    name: "匈牙利",
    nameEn: "Hungary",
    nameJa: "ハンガリー",
    nameKo: "헝가리",
    nameOriginal: "Magyarország",
    currency: "HUF",
    flag: flag("HU"),
    group: "europe",
    appleUrl: "https://www.apple.com/hu/",
  },
  {
    code: "ro",
    name: "罗马尼亚",
    nameEn: "Romania",
    nameJa: "ルーマニア",
    nameKo: "루마니아",
    nameOriginal: "România",
    currency: "RON",
    flag: flag("RO"),
    group: "europe",
    appleUrl: "https://www.apple.com/ro/",
  },
  {
    code: "sk",
    name: "斯洛伐克",
    nameEn: "Slovakia",
    nameJa: "スロバキア",
    nameKo: "슬로바키아",
    nameOriginal: "Slovensko",
    currency: "EUR",
    flag: flag("SK"),
    group: "europe",
    appleUrl: "https://www.apple.com/sk/",
  },
  {
    code: "si",
    name: "斯洛文尼亚",
    nameEn: "Slovenia",
    nameJa: "スロベニア",
    nameKo: "슬로베니아",
    nameOriginal: "Slovenia",
    currency: "EUR",
    flag: flag("SI"),
    group: "europe",
    appleUrl: "https://www.apple.com/si/",
  },
  {
    code: "bg",
    name: "保加利亚",
    nameEn: "Bulgaria",
    nameJa: "ブルガリア",
    nameKo: "불가리아",
    nameOriginal: "Bulgaria",
    currency: "BGN",
    flag: flag("BG"),
    group: "europe",
    appleUrl: "https://www.apple.com/bg/",
  },
  {
    code: "hr",
    name: "克罗地亚",
    nameEn: "Croatia",
    nameJa: "クロアチア",
    nameKo: "크로아티아",
    nameOriginal: "Hrvatska",
    currency: "EUR",
    flag: flag("HR"),
    group: "europe",
    appleUrl: "https://www.apple.com/hr/",
  },
  {
    code: "ee",
    name: "爱沙尼亚",
    nameEn: "Estonia",
    nameJa: "エストニア",
    nameKo: "에스토니아",
    nameOriginal: "Eesti",
    currency: "EUR",
    flag: flag("EE"),
    group: "europe",
    appleUrl: "https://www.apple.com/ee/",
  },
  {
    code: "lv",
    name: "拉脱维亚",
    nameEn: "Latvia",
    nameJa: "ラトビア",
    nameKo: "라트비아",
    nameOriginal: "Latvija",
    currency: "EUR",
    flag: flag("LV"),
    group: "europe",
    appleUrl: "https://www.apple.com/lv/",
  },
  {
    code: "lt",
    name: "立陶宛",
    nameEn: "Lithuania",
    nameJa: "リトアニア",
    nameKo: "리투아니아",
    nameOriginal: "Lietuva",
    currency: "EUR",
    flag: flag("LT"),
    group: "europe",
    appleUrl: "https://www.apple.com/lt/",
  },
  {
    code: "lu",
    name: "卢森堡",
    nameEn: "Luxembourg",
    nameJa: "ルクセンブルク",
    nameKo: "룩셈부르크",
    nameOriginal: "Luxembourg",
    currency: "EUR",
    flag: flag("LU"),
    group: "europe",
    appleUrl: "https://www.apple.com/lu/",
  },
  {
    code: "mt",
    name: "马耳他",
    nameEn: "Malta",
    nameJa: "マルタ",
    nameKo: "몰타",
    nameOriginal: "Malta",
    currency: "EUR",
    flag: flag("MT"),
    group: "europe",
    appleUrl: "https://www.apple.com/mt/",
  },
  {
    code: "li",
    name: "列支敦士登",
    nameEn: "Liechtenstein",
    nameJa: "リヒテンシュタイン",
    nameKo: "리히텐슈타인",
    nameOriginal: "Liechtenstein",
    currency: "CHF",
    flag: flag("LI"),
    group: "europe",
    appleUrl: "https://www.apple.com/li/",
  },
  {
    code: "ua",
    name: "乌克兰",
    nameEn: "Ukraine",
    nameJa: "ウクライナ",
    nameKo: "우크라이나",
    nameOriginal: "Yкраїна",
    currency: "UAH",
    flag: flag("UA"),
    group: "europe",
    appleUrl: "https://www.apple.com/ua/",
  },
  {
    code: "by",
    name: "白俄罗斯",
    nameEn: "Belarus",
    nameJa: "ベラルーシ",
    nameKo: "벨라루스",
    nameOriginal: "Belarus",
    currency: "BYN",
    flag: flag("BY"),
    group: "europe",
    appleUrl: "https://www.apple.com/by/",
  },
  {
    code: "md",
    name: "摩尔多瓦",
    nameEn: "Moldova",
    nameJa: "モルドバ",
    nameKo: "몰도바",
    nameOriginal: "Moldova",
    currency: "MDL",
    flag: flag("MD"),
    group: "europe",
    appleUrl: "https://www.apple.com/md/",
  },
  {
    code: "me",
    name: "黑山",
    nameEn: "Montenegro",
    nameJa: "モンテネグロ",
    nameKo: "몬테네그로",
    nameOriginal: "Montenegro",
    currency: "EUR",
    flag: flag("ME"),
    group: "europe",
    appleUrl: "https://www.apple.com/me/",
  },
  {
    code: "mk",
    name: "北马其顿",
    nameEn: "North Macedonia",
    nameJa: "北マケドニア",
    nameKo: "북마케도니아",
    nameOriginal: "North Macedonia",
    currency: "MKD",
    flag: flag("MK"),
    group: "europe",
    appleUrl: "https://www.apple.com/mk/",
  },
  {
    code: "ge",
    name: "格鲁吉亚",
    nameEn: "Georgia",
    nameJa: "ジョージア",
    nameKo: "조지아",
    nameOriginal: "Georgia",
    currency: "GEL",
    flag: flag("GE"),
    group: "europe",
    appleUrl: "https://www.apple.com/ge/",
  },
  {
    code: "am",
    name: "亚美尼亚",
    nameEn: "Armenia",
    nameJa: "アルメニア",
    nameKo: "아르메니아",
    nameOriginal: "Armenia",
    currency: "AMD",
    flag: flag("AM"),
    group: "europe",
    appleUrl: "https://www.apple.com/am/",
  },
  {
    code: "az",
    name: "阿塞拜疆",
    nameEn: "Azerbaijan",
    nameJa: "アゼルバイジャン",
    nameKo: "아제르바이잔",
    nameOriginal: "Azerbaijan",
    currency: "AZN",
    flag: flag("AZ"),
    group: "europe",
    appleUrl: "https://www.apple.com/az/",
  },
  {
    code: "kz",
    name: "哈萨克斯坦",
    nameEn: "Kazakhstan",
    nameJa: "カザフスタン",
    nameKo: "카자흐스탄",
    nameOriginal: "Kazakhstan",
    currency: "KZT",
    flag: flag("KZ"),
    group: "europe",
    appleUrl: "https://www.apple.com/kz/",
  },
  {
    code: "kg",
    name: "吉尔吉斯斯坦",
    nameEn: "Kyrgyzstan",
    nameJa: "キルギス",
    nameKo: "키르기스스탄",
    nameOriginal: "Kyrgyzstan",
    currency: "KGS",
    flag: flag("KG"),
    group: "europe",
    appleUrl: "https://www.apple.com/kg/",
  },
  {
    code: "tj",
    name: "塔吉克斯坦",
    nameEn: "Tajikistan",
    nameJa: "タジキスタン",
    nameKo: "타지키스탄",
    nameOriginal: "Tajikistan",
    currency: "TJS",
    flag: flag("TJ"),
    group: "europe",
    appleUrl: "https://www.apple.com/tj/",
  },
  {
    code: "tm",
    name: "土库曼斯坦",
    nameEn: "Turkmenistan",
    nameJa: "トルクメニスタン",
    nameKo: "투르크메니스탄",
    nameOriginal: "Turkmenistan",
    currency: "TMT",
    flag: flag("TM"),
    group: "europe",
    appleUrl: "https://www.apple.com/tm/",
  },
  {
    code: "uz",
    name: "乌兹别克斯坦",
    nameEn: "Uzbekistan",
    nameJa: "ウズベキスタン",
    nameKo: "우즈베키스탄",
    nameOriginal: "Uzbekistan",
    currency: "UZS",
    flag: flag("UZ"),
    group: "europe",
    appleUrl: "https://www.apple.com/uz/",
  },

  // ============ 中东与非洲 ============
  {
    code: "sa",
    name: "沙特阿拉伯",
    nameEn: "Saudi Arabia",
    nameJa: "サウジアラビア",
    nameKo: "사우디아라비아",
    nameOriginal: "Saudi Arabia",
    currency: "SAR",
    flag: flag("SA"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/sa/",
  },
  {
    code: "ae",
    name: "阿联酋",
    nameEn: "United Arab Emirates",
    nameJa: "アラブ首長国連邦",
    nameKo: "아랍에미리트",
    nameOriginal: "United Arab Emirates",
    currency: "AED",
    flag: flag("AE"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ae/",
  },
  {
    code: "il",
    name: "以色列",
    nameEn: "Israel",
    nameJa: "イスラエル",
    nameKo: "이스라엘",
    nameOriginal: "Israel",
    currency: "ILS",
    flag: flag("IL"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/il/",
  },
  {
    code: "eg",
    name: "埃及",
    nameEn: "Egypt",
    nameJa: "エジプト",
    nameKo: "이집트",
    nameOriginal: "Egypt",
    currency: "EGP",
    flag: flag("EG"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/eg/",
  },
  {
    code: "ng",
    name: "尼日利亚",
    nameEn: "Nigeria",
    nameJa: "ナイジェリア",
    nameKo: "나이지리아",
    nameOriginal: "Nigeria",
    currency: "NGN",
    flag: flag("NG"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ng/",
  },
  {
    code: "za",
    name: "南非",
    nameEn: "South Africa",
    nameJa: "南アフリカ",
    nameKo: "남아프리카 공화국",
    nameOriginal: "South Africa",
    currency: "ZAR",
    flag: flag("ZA"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/za/",
  },
  {
    code: "bh",
    name: "巴林",
    nameEn: "Bahrain",
    nameJa: "バーレーン",
    nameKo: "바레인",
    nameOriginal: "Bahrain",
    currency: "BHD",
    flag: flag("BH"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/bh/",
  },
  {
    code: "jo",
    name: "约旦",
    nameEn: "Jordan",
    nameJa: "ヨルダン",
    nameKo: "요르단",
    nameOriginal: "Jordan",
    currency: "JOD",
    flag: flag("JO"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/jo/",
  },
  {
    code: "kw",
    name: "科威特",
    nameEn: "Kuwait",
    nameJa: "クウェート",
    nameKo: "쿠웨이트",
    nameOriginal: "Kuwait",
    currency: "KWD",
    flag: flag("KW"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/kw/",
  },
  {
    code: "om",
    name: "阿曼",
    nameEn: "Oman",
    nameJa: "オマーン",
    nameKo: "오만",
    nameOriginal: "Oman",
    currency: "OMR",
    flag: flag("OM"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/om/",
  },
  {
    code: "qa",
    name: "卡塔尔",
    nameEn: "Qatar",
    nameJa: "カタール",
    nameKo: "카타르",
    nameOriginal: "Qatar",
    currency: "QAR",
    flag: flag("QA"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/qa/",
  },
  {
    code: "ke",
    name: "肯尼亚",
    nameEn: "Kenya",
    nameJa: "ケニア",
    nameKo: "케냐",
    nameOriginal: "Kenya",
    currency: "KES",
    flag: flag("KE"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ke/",
  },
  {
    code: "ug",
    name: "乌干达",
    nameEn: "Uganda",
    nameJa: "ウガンダ",
    nameKo: "우간다",
    nameOriginal: "Uganda",
    currency: "UGX",
    flag: flag("UG"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ug/",
  },
  {
    code: "tn",
    name: "突尼斯",
    nameEn: "Tunisia",
    nameJa: "チュニジア",
    nameKo: "튀니지",
    nameOriginal: "Tunisie",
    currency: "TND",
    flag: flag("TN"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/tn/",
  },
  {
    code: "ma",
    name: "摩洛哥",
    nameEn: "Morocco",
    nameJa: "モロッコ",
    nameKo: "모로코",
    nameOriginal: "Maroc",
    currency: "MAD",
    flag: flag("MA"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ma/",
  },
  {
    code: "mu",
    name: "毛里求斯",
    nameEn: "Mauritius",
    nameJa: "モーリシャス",
    nameKo: "모리셔스",
    nameOriginal: "Maurice",
    currency: "MUR",
    flag: flag("MU"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/mu/",
  },
  {
    code: "sn",
    name: "塞内加尔",
    nameEn: "Senegal",
    nameJa: "セネガル",
    nameKo: "세네갈",
    nameOriginal: "Sénégal",
    currency: "XOF",
    flag: flag("SN"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/sn/",
  },
  {
    code: "bw",
    name: "博茨瓦纳",
    nameEn: "Botswana",
    nameJa: "ボツワナ",
    nameKo: "보츠와나",
    nameOriginal: "Botswana",
    currency: "BWP",
    flag: flag("BW"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/bw/",
  },
  {
    code: "mz",
    name: "莫桑比克",
    nameEn: "Mozambique",
    nameJa: "モザンビーク",
    nameKo: "모잠비크",
    nameOriginal: "Mozambique",
    currency: "MZN",
    flag: flag("MZ"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/mz/",
  },
  {
    code: "cm",
    name: "喀麦隆",
    nameEn: "Cameroon",
    nameJa: "カメルーン",
    nameKo: "카메룬",
    nameOriginal: "Cameroun",
    currency: "XAF",
    flag: flag("CM"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/cm/",
  },
  {
    code: "ci",
    name: "科特迪瓦",
    nameEn: "Côte d'Ivoire",
    nameJa: "コートジボワール",
    nameKo: "코트디부아르",
    nameOriginal: "Côte d'Ivoire",
    currency: "XOF",
    flag: flag("CI"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ci/",
  },
  {
    code: "mg",
    name: "马达加斯加",
    nameEn: "Madagascar",
    nameJa: "マダガスカル",
    nameKo: "마다가스카르",
    nameOriginal: "Madagascar",
    currency: "MGA",
    flag: flag("MG"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/mg/",
  },
  {
    code: "ml",
    name: "马里",
    nameEn: "Mali",
    nameJa: "マリ",
    nameKo: "말리",
    nameOriginal: "Mali",
    currency: "XOF",
    flag: flag("ML"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ml/",
  },
  {
    code: "ne",
    name: "尼日尔",
    nameEn: "Niger",
    nameJa: "ニジェール",
    nameKo: "니제르",
    nameOriginal: "Niger",
    currency: "XOF",
    flag: flag("NE"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/ne/",
  },
  {
    code: "gn",
    name: "几内亚",
    nameEn: "Guinea",
    nameJa: "ギニア",
    nameKo: "기니",
    nameOriginal: "Guinée",
    currency: "GNF",
    flag: flag("GN"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/gn/",
  },
  {
    code: "gw",
    name: "几内亚比绍",
    nameEn: "Guinea-Bissau",
    nameJa: "ギニアビサウ",
    nameKo: "기니비사우",
    nameOriginal: "Guinea-Bissau",
    currency: "XOF",
    flag: flag("GW"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/gw/",
  },
  {
    code: "gq",
    name: "赤道几内亚",
    nameEn: "Equatorial Guinea",
    nameJa: "赤道ギニア",
    nameKo: "적도 기니",
    nameOriginal: "Guinée Equatoriale",
    currency: "XAF",
    flag: flag("GQ"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/gq/",
  },
  {
    code: "cf",
    name: "中非共和国",
    nameEn: "Central African Republic",
    nameJa: "中央アフリカ",
    nameKo: "중앙아프리카 공화국",
    nameOriginal: "République Centrafricaine",
    currency: "XAF",
    flag: flag("CF"),
    group: "middle-east-africa",
    appleUrl: "https://www.apple.com/cf/",
  },
];

/** 默认展示的地区（热门 + 低价区） */
export const DEFAULT_REGIONS = [
  // 热门
  "cn",
  "us",
  "jp",
  "hk",
  "tw",
  "kr",
  "gb",
  "de",
  // 低价区
  "tr",
  "in",
  "ar",
  "eg",
  "ng",
];

/** 按分组获取地区 */
export function getRegionsByGroup(): Record<RegionGroup, Region[]> {
  const grouped: Record<RegionGroup, Region[]> = {
    "asia-pacific": [],
    europe: [],
    americas: [],
    "middle-east-africa": [],
  };
  for (const region of REGIONS) {
    grouped[region.group].push(region);
  }
  return grouped;
}

/** 根据代码查找地区 */
export function getRegionByCode(code: string): Region | undefined {
  return REGIONS.find((r) => r.code === code);
}

/** 根据 locale 获取地区显示名称 */
export function getRegionName(region: Region, locale: Locale): string {
  switch (locale) {
    case "zh": return region.name;
    case "en": return region.nameEn;
    case "ja": return region.nameJa;
    case "ko": return region.nameKo;
    case "ru": return region.nameEn;
  }
}
